name: Deploy Blog

on:
  push:
    branches:
      - master  # 只在 main 分支发生变化时触发
    paths:
      - 'p/*'
      - 'lib/update_list.py'
      - 'index.html'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown

      - name: Run update_list.py
        run: python lib/update_list.py

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # 部署到 gh-pages 分支
          folder: .  # 部署根目录
